---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  #require_chef_omnibus: 12.4.1

platforms:
  - name: windows
    driver_config:
        box: Win2012R2-dotnet35enabled
        box_url: http://nexus.lab.brainshark.com/vagrant-boxes/w2k12r2-dotnet35enabled.box
        communicator: winrm
        vm_hostname: false
        gui: true
        cpus: 2
        network:
        - ["forwarded_port", {guest: 5985, host: 55985, id: "winrm", auto_correct: true}]
        - ["forwarded_port", {guest: 3389, host: 33389, id: "rdp", auto_correct: true}]
    transport:
        name: winrm

suites:
  - name: default
    run_list:
        - recipe[ntrights::default]
    attributes:
